<script setup lang="ts">
/**
 * ChatRoomList — 참여 중인 채팅방 목록
 * 레퍼런스: "Chat" 큰 타이틀 + pill 검색바 + 아바타 아이템
 */
import { ref, computed } from 'vue'
import type { ChatRoom } from '../../types/chat'
import ChatRoomItem from './ChatRoomItem.vue'
import ChatAvatar from './ChatAvatar.vue'
import { useAtlasChatStore } from '../../stores/chat'
import { useAtlasSessionStore } from '../../stores/session'
import { useAtlasPreferencesStore } from '../../stores/preferences'

const props = defineProps<{
  rooms: ChatRoom[]
}>()

const emit = defineEmits<{
  selectRoom: [roomPublicId: string]
}>()

const chatStore = useAtlasChatStore()
const sessionStore = useAtlasSessionStore()
const preferences = useAtlasPreferencesStore()

const searchQuery = ref('')
const isCreatingRoom = ref(false)
const userSearchQuery = ref('')
const selectedUsers = ref<string[]>([])

const copy = computed(() => ({
  roomSearchPlaceholder: preferences.language === 'ko' ? '채팅방 검색...' : 'Search chat rooms...',
  createRoomTitle: preferences.language === 'ko' ? '채팅방 생성' : 'Create chat room',
  cancelCreateTitle: preferences.language === 'ko' ? '채팅방 생성 취소' : 'Cancel chat room creation',
  inviteSearchPlaceholder: preferences.language === 'ko' ? '초대할 사용자 검색...' : 'Search users to invite...',
  noSearchResults: preferences.language === 'ko' ? '검색 결과가 없습니다.' : 'No search results.',
  startChat: preferences.language === 'ko' ? '채팅 시작' : 'Start Chat',
  pinned: preferences.language === 'ko' ? '고정됨' : 'PINNED',
  noRooms: preferences.language === 'ko' ? '채팅방이 없습니다.' : 'No chat rooms.',
  me: preferences.language === 'ko' ? '나' : 'Me',
}))

const currentUserDisplayName = computed(() => {
  const me = chatStore.availableUsers.find(u => u.userPublicId === chatStore.currentUserPublicId)
  return me?.displayName || sessionStore.loginId || copy.value.me
})

const filteredAvailableUsers = computed(() => {
  const q = userSearchQuery.value.trim().toLowerCase()
  let users = chatStore.availableUsers.filter(u => u.userPublicId !== chatStore.currentUserPublicId)
  if (q) {
    users = users.filter((u) => u.displayName.toLowerCase().includes(q))
  }
  return users
})

const filteredRooms = computed(() => {
  const q = searchQuery.value.trim().toLowerCase()
  let result = [...props.rooms]
  if (q) {
    result = result.filter((room) => room.roomName && room.roomName.toLowerCase().includes(q))
  }
  return result
})

// 고정방: pinnedAt 내림차순 (최근 고정 = 최상단)
const pinnedRooms = computed(() =>
  filteredRooms.value
    .filter(r => !!r.pinnedAt)
    .sort((a, b) => new Date(b.pinnedAt!).getTime() - new Date(a.pinnedAt!).getTime())
)

// 비고정방: 최신 메시지 순
const unpinnedRooms = computed(() =>
  filteredRooms.value
    .filter(r => !r.pinnedAt)
    .sort((a, b) => {
      const timeA = a.lastMessage?.sentAt ? new Date(a.lastMessage.sentAt).getTime() : 0
      const timeB = b.lastMessage?.sentAt ? new Date(b.lastMessage.sentAt).getTime() : 0
      return timeB - timeA
    })
)

function handlePin(roomPublicId: string) {
  chatStore.pinRoom(roomPublicId)
}

function handleUnpin(roomPublicId: string) {
  chatStore.unpinRoom(roomPublicId)
}

async function handleCreateRoom() {
  if (selectedUsers.value.length === 0) return
  
  // 선택된 유저 정보 가져와서 방 이름 자동 조합
  const selectedDisplayNames = selectedUsers.value.map(id => {
    const user = chatStore.availableUsers.find(u => u.userPublicId === id)
    return user ? user.displayName : 'Unknown'
  })
  
  const autoGeneratedName = [currentUserDisplayName.value, ...selectedDisplayNames].join(', ')
  
  // 선택된 유저로 방 생성
  const newRoomId = await chatStore.createRoom(autoGeneratedName, selectedUsers.value)
  isCreatingRoom.value = false
  userSearchQuery.value = ''
  selectedUsers.value = []
  
  if (newRoomId) {
    emit('selectRoom', newRoomId)
  }
}

function toggleCreateRoomMode() {
  isCreatingRoom.value = !isCreatingRoom.value
  if (isCreatingRoom.value) {
    chatStore.fetchAvailableUsers()
  }
}
</script>

<template>
  <div class="chat-room-list">
    <!-- 검색바 (pill 형태) -->
    <div v-if="!isCreatingRoom" class="chat-room-list__search-wrapper">
      <div class="chat-room-list__search-row">
        <div class="chat-room-list__search">
          <span class="material-symbols-outlined">search</span>
          <input
            v-model="searchQuery"
            type="text"
            :placeholder="copy.roomSearchPlaceholder"
          />
        </div>

        <button
          class="chat-room-list__add-btn"
          type="button"
          :title="copy.createRoomTitle"
          @click="toggleCreateRoomMode"
        >
          <span class="material-symbols-outlined">add</span>
        </button>
      </div>
    </div>

    <!-- 채팅방 생성 모드 -->
    <div v-if="isCreatingRoom" class="chat-room-list__create-panel">
      <div class="chat-room-list__create-search-row">
        <div class="chat-room-list__create-search">
          <span class="material-symbols-outlined">person_search</span>
          <input
            v-model="userSearchQuery"
            type="text"
            :placeholder="copy.inviteSearchPlaceholder"
          />
        </div>

        <button
          class="chat-room-list__add-btn"
          type="button"
          :title="copy.cancelCreateTitle"
          @click="toggleCreateRoomMode"
        >
          <span class="material-symbols-outlined">close</span>
        </button>
      </div>
      <div class="chat-room-list__create-users">
        <label v-for="user in filteredAvailableUsers" :key="user.userPublicId" class="chat-room-list__invite-user">
          <input type="checkbox" :value="user.userPublicId" v-model="selectedUsers" />
          <ChatAvatar
            :image-url="user.profileImageThumbPath || undefined"
            :name="user.displayName"
            size="sm"
          />
          <span class="chat-room-list__invite-copy">
            <span>{{ user.displayName }}</span>
            <span v-if="user.jobTitle" class="chat-room-list__invite-role">{{ user.jobTitle }}</span>
          </span>
        </label>
        <div v-if="filteredAvailableUsers.length === 0" class="chat-room-list__create-empty">
          {{ copy.noSearchResults }}
        </div>
      </div>
      <button
        class="chat-room-list__create-submit"
        :disabled="selectedUsers.length === 0"
        @click="handleCreateRoom"
      >
        {{ copy.startChat }} ({{ selectedUsers.length }})
      </button>
    </div>

    <!-- 채팅방 목록 -->
    <div class="chat-room-list__items" v-if="!isCreatingRoom">
      <!-- 고정된 방 -->
      <ChatRoomItem
        v-for="room in pinnedRooms"
        :key="room.publicId"
        :room="room"
        :current-user-public-id="chatStore.currentUserPublicId"
        @select="emit('selectRoom', $event)"
        @pin="handlePin"
        @unpin="handleUnpin"
      />
      <!-- 구분선 -->
      <div v-if="pinnedRooms.length > 0 && unpinnedRooms.length > 0" class="chat-room-list__pin-divider">
        <span>{{ copy.pinned }}</span>
      </div>
      <!-- 비고정 방 -->
      <ChatRoomItem
        v-for="room in unpinnedRooms"
        :key="room.publicId"
        :room="room"
        :current-user-public-id="chatStore.currentUserPublicId"
        @select="emit('selectRoom', $event)"
        @pin="handlePin"
        @unpin="handleUnpin"
      />
      <div v-if="filteredRooms.length === 0" class="chat-room-list__empty">
        <span class="material-symbols-outlined">forum</span>
        <p>{{ copy.noRooms }}</p>
      </div>
    </div>
  </div>
</template>
