<script setup lang="ts">
/**
 * ChatRoomList — 참여 중인 채팅방 목록
 * 검색 필터 + 채팅방 아이템 렌더링 + 채팅방 생성
 */
import { ref, computed } from 'vue'
import type { ChatRoom } from '../../types/chat'
import ChatRoomItem from './ChatRoomItem.vue'
import { useAtlasChatStore } from '../../stores/chat'

import { useAtlasSessionStore } from '../../stores/session'

const props = defineProps<{
  rooms: ChatRoom[]
}>()

const emit = defineEmits<{
  selectRoom: [roomPublicId: string]
}>()

const chatStore = useAtlasChatStore()
const sessionStore = useAtlasSessionStore()

const searchQuery = ref('')
const isCreatingRoom = ref(false)
const userSearchQuery = ref('')
const selectedUsers = ref<string[]>([])

const currentUserDisplayName = computed(() => {
  const me = chatStore.availableUsers.find(u => u.userPublicId === chatStore.currentUserPublicId)
  return me?.displayName || sessionStore.user?.userName || '나'
})

const filteredAvailableUsers = computed(() => {
  const q = userSearchQuery.value.trim().toLowerCase()
  let users = chatStore.availableUsers.filter(u => u.userPublicId !== chatStore.currentUserPublicId)
  if (q) {
    users = users.filter((u) => u.displayName.toLowerCase().includes(q))
  }
  return users
})

const filteredRooms = computed(() => {
  const q = searchQuery.value.trim().toLowerCase()
  if (!q) return props.rooms
  return props.rooms.filter((room) => room.roomName && room.roomName.toLowerCase().includes(q))
})

async function handleCreateRoom() {
  if (selectedUsers.value.length === 0) return
  
  // 선택된 유저 정보 가져와서 방 이름 자동 조합
  const selectedDisplayNames = selectedUsers.value.map(id => {
    const user = chatStore.availableUsers.find(u => u.userPublicId === id)
    return user ? user.displayName : 'Unknown'
  })
  
  const autoGeneratedName = [currentUserDisplayName.value, ...selectedDisplayNames].join(', ')
  
  // 선택된 유저로 방 생성
  const newRoomId = await chatStore.createRoom(autoGeneratedName, selectedUsers.value)
  isCreatingRoom.value = false
  userSearchQuery.value = ''
  selectedUsers.value = []
  
  if (newRoomId) {
    emit('selectRoom', newRoomId)
  }
}

function toggleCreateRoomMode() {
  isCreatingRoom.value = !isCreatingRoom.value
  if (isCreatingRoom.value) {
    chatStore.fetchAvailableUsers()
  }
}
</script>

<template>
  <div class="chat-room-list">
    <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 16px; padding: 0 16px; margin-top: 16px;">
      <div class="chat-room-list__search" style="flex: 1; margin: 0;">
        <span class="material-symbols-outlined">search</span>
        <input
          v-model="searchQuery"
          type="text"
          placeholder="채팅방 검색..."
        />
      </div>
      <button 
        class="chat-room-list__create-btn" 
        style="background: transparent; border: 1px solid var(--color-outline, #474747); color: inherit; width: 36px; height: 36px; display: flex; align-items: center; justify-content: center; cursor: pointer; border-radius: 0;"
        @click="toggleCreateRoomMode" 
        title="채팅방 생성">
        <span class="material-symbols-outlined">{{ isCreatingRoom ? 'close' : 'add' }}</span>
      </button>
    </div>

    <div v-if="isCreatingRoom" style="padding: 0 16px 16px; border-bottom: 1px solid var(--color-surface-container-low, #1E1E1E);">
      <div style="display: flex; align-items: center; border-bottom: 2px solid var(--color-outline, #474747); margin-bottom: 8px;">
        <span class="material-symbols-outlined" style="font-size: 1rem; margin-right: 4px; color: var(--color-on-surface-variant, #C6C6C6);">search</span>
        <input
          v-model="userSearchQuery"
          type="text"
          placeholder="초대할 사용자 검색..."
          style="width: 100%; padding: 8px 0; background: transparent; border: none; color: inherit; outline: none;"
        />
      </div>
      <div style="max-height: 120px; overflow-y: auto; margin-bottom: 16px; font-size: 0.875rem;">
        <label v-for="user in filteredAvailableUsers" :key="user.userPublicId" style="display: block; padding: 4px 0; cursor: pointer; color: var(--color-on-surface, #FFFFFF);">
          <input type="checkbox" :value="user.userPublicId" v-model="selectedUsers" style="margin-right: 8px;" />
          {{ user.displayName }} <span v-if="user.jobTitle" style="color: var(--color-on-surface-variant, #C6C6C6); font-size: 0.75rem;">({{ user.jobTitle }})</span>
        </label>
        <div v-if="filteredAvailableUsers.length === 0" style="padding: 8px 0; color: var(--color-on-surface-variant, #C6C6C6); font-size: 0.75rem; text-align: center;">검색 결과가 없습니다.</div>
      </div>
      <button 
        @click="handleCreateRoom"
        :disabled="selectedUsers.length === 0"
        style="width: 100%; padding: 8px; background: var(--color-primary, #FFFFFF); color: var(--color-on-primary, #121212); border: none; cursor: pointer; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;"
        :style="{ opacity: selectedUsers.length === 0 ? 0.5 : 1, cursor: selectedUsers.length === 0 ? 'not-allowed' : 'pointer' }">
        채팅 시작 ({{ selectedUsers.length }}명)
      </button>
    </div>

    <div class="chat-room-list__items" v-if="!isCreatingRoom">
      <ChatRoomItem
        v-for="room in filteredRooms"
        :key="room.publicId"
        :room="room"
        @select="emit('selectRoom', $event)"
      />
      <div v-if="filteredRooms.length === 0" class="chat-room-list__empty">
        <span class="material-symbols-outlined">forum</span>
        <p>채팅방이 없습니다.</p>
      </div>
    </div>
  </div>
</template>
