import type { AppLanguage } from '../types'

const KO_DEFAULT_COPY: Record<string, string> = {
  Modal: '모달',
  'Close modal': '모달 닫기',
  OPEN: '열기',
  DETAILS: '상세',
  OPEN_ORCHESTRATION: '오케스트레이션 실행',
  EXPORT_DATA: '데이터 내보내기',
  NOTIFICATION_POLICY: '알림 정책',
  EDIT_PROFILE: '프로필 수정',
  SIGN_OUT: '로그아웃',
  'Blueprint Map': '블루프린트 맵',
  'Interactive Map': '인터랙티브 맵',
  'CSV Export': 'CSV 내보내기',
  'JSON Snapshot': 'JSON 스냅샷',
  'ACTIVE EXPOSURE': '활성 노출량',
  'mt in risk lanes': '리스크 레인 물동량(mt)',
  'RECOVERY ETA': '복구 ETA',
  'BEST-CASE MEDIAN': '최선 시나리오 중앙값',
  'WAREHOUSE CAPACITY': '창고 수용량',
  'REROUTE READINESS': '우회 준비도',
  'CRITICAL EVENTS': '중요 이벤트',
  'Partner ID': '파트너 ID',
  Entity: '업체명',
  Status: '상태',
  '+6.4% QoQ': '전분기 대비 +6.4%',
  'Monitoring // Control Tower': '모니터링 // 컨트롤 타워',
  'Monitoring // Orders': '모니터링 // 영향 발주',
  'Monitoring // Orders Desk': '모니터링 // 발주 관리',
  'Monitoring // Supplier Control': '모니터링 // 협력사 관리',
  'Monitoring // Network': '모니터링 // 공급망 네트워크',
  'Monitoring // Certificates': '모니터링 // 인증 감시',
  'Response // Events': '대응 // 리스크 이벤트',
  'Response // Recovery': '대응 // 복구 추적',
  'Response // Documents': '대응 // 문서 및 인증',
  'Response // Recommendations': '대응 // 권고안',
  'Response // ESG': '대응 // ESG',
  'Governance // Board': '거버넌스 // 의사결정',
  'Governance // Audit': '거버넌스 // 감사',
  'Governance // Collaboration': '거버넌스 // 협업',
  'Governance // Notifications': '거버넌스 // 알림',
  'Governance // Rules': '거버넌스 // 규칙',
  'Control Tower': '컨트롤 타워',
  'Impact Orders Board': '영향 발주 보드',
  'Purchase Order Board': '발주 보드',
  'Supplier Master Desk': '협력사 마스터 데스크',
  'Global Partner Map': '글로벌 파트너 맵',
  'Expiry & Quality Monitor': '만료 및 품질 모니터',
  'Risk Event Desk': '리스크 이벤트 데스크',
  'Execution Timeline': '실행 타임라인',
  'Document Trace Desk': '문서 추적 데스크',
  'Alternative Decision Desk': '대체 의사결정 데스크',
  'ESG-Aware Scoring Desk': 'ESG 반영 점수 데스크',
  'Decision Governance Board': '의사결정 거버넌스 보드',
  'Governance Ledger': '거버넌스 원장',
  'Ops Collaboration Room': '운영 협업 룸',
  'Alert Channel Center': '알림 채널 센터',
  'Rule & Escalation Matrix': '규칙 및 에스컬레이션 매트릭스',
  KPI: '핵심 지표',
  STATUS: '상태',
  QUEUE: '대기열',
  Snapshot: '스냅샷',
  Queue: '대기열',
  Updates: '업데이트',
  Owner: '담당',
  Focus: '초점',
  Region: '영역',
  Item: '항목',
  State: '상태',
  LIVE: '실시간',
  OPS: '운영',
  NOTES: '노트',
  'impacted orders': '영향 주문',
  Stable: '안정',
  'workflow healthy': '워크플로 정상',
  'actions pending': '대기 액션',
  'priority orders': '우선순위 발주',
  Watch: '주의',
  '2 escalations': '에스컬레이션 2건',
  'approval waits': '승인 대기',
  Busy: '혼잡',
  'buyer review': '발주사 검토',
  'eta changes': 'ETA 변경',
  'managed partners': '관리 협력사',
  Normal: '정상',
  'quality stable': '품질 안정',
  'onboarding items': '온보딩 항목',
  'active suppliers': '활성 협력사',
  High: '높음',
  'network volatility': '네트워크 변동성',
  'risk clusters': '리스크 군집',
  'certificates due': '만료 예정 인증',
  Risk: '리스크',
  'lot mismatch': 'lot 불일치',
  'quality holds': '품질 보류',
  'active events': '활성 이벤트',
  Action: '조치 중',
  'orchestration running': '오케스트레이션 실행 중',
  'eta recoveries': 'ETA 회복 과제',
  'eta recovery': 'ETA 회복률',
  'On Track': '정상 진행',
  '3 milestones done': '마일스톤 3건 완료',
  'blocked tasks': '차단된 작업',
  'tracked docs': '추적 문서',
  'audit synced': '감사 동기화',
  'missing evidence': '누락 증빙',
  'active options': '활성 대안',
  Review: '검토 중',
  'governance pending': '거버넌스 대기',
  'accepted paths': '수용 경로',
  'esg alerts': 'ESG 경보',
  Adjusted: '조정됨',
  'scores updated': '점수 반영 완료',
  'suppliers tracked': '추적 협력사',
  'reviews open': '진행 중 검토',
  Board: '위원회 검토',
  'post-evals due': '사후평가 대기',
  'ledger entries': '원장 기록',
  Clean: '정상',
  'log integrity': '로그 무결성',
  'follow-ups': '후속 조치',
  'active threads': '활성 스레드',
  Live: '실시간',
  'channel healthy': '채널 정상',
  'mentions pending': '멘션 대기',
  'alerts today': '오늘 알림',
  Unread: '미확인',
  '5 need action': '조치 필요 5건',
  'policy gaps': '정책 공백',
  'active rules': '활성 규칙',
  Valid: '유효',
  'threshold synced': '임계치 동기화',
  'pending edits': '수정 대기',
  'Impact Monitoring Core Snapshot': '영향 모니터링 핵심 스냅샷',
  'Impact Monitoring Core Queue': '영향 모니터링 핵심 대기열',
  'Impact Monitoring Core Feed': '영향 모니터링 핵심 피드',
  'Impact Orders Board Snapshot': '영향 발주 보드 스냅샷',
  'Impact Orders Board Queue': '영향 발주 보드 대기열',
  'Impact Orders Board Feed': '영향 발주 보드 피드',
  'Purchase Order Board Snapshot': '발주 보드 스냅샷',
  'Purchase Order Board Queue': '발주 보드 대기열',
  'Purchase Order Board Feed': '발주 보드 피드',
  'Supplier Master Desk Snapshot': '협력사 마스터 데스크 스냅샷',
  'Supplier Master Desk Queue': '협력사 마스터 데스크 대기열',
  'Supplier Master Desk Feed': '협력사 마스터 데스크 피드',
  'Global Partner Map Snapshot': '글로벌 파트너 맵 스냅샷',
  'Global Partner Map Queue': '글로벌 파트너 맵 대기열',
  'Global Partner Map Feed': '글로벌 파트너 맵 피드',
  'Expiry & Quality Monitor Snapshot': '만료 및 품질 모니터 스냅샷',
  'Expiry & Quality Monitor Queue': '만료 및 품질 모니터 대기열',
  'Expiry & Quality Monitor Feed': '만료 및 품질 모니터 피드',
  'Risk Event Desk Snapshot': '리스크 이벤트 데스크 스냅샷',
  'Risk Event Desk Queue': '리스크 이벤트 데스크 대기열',
  'Risk Event Desk Feed': '리스크 이벤트 데스크 피드',
  'Execution Timeline Snapshot': '실행 타임라인 스냅샷',
  'Execution Timeline Queue': '실행 타임라인 대기열',
  'Execution Timeline Feed': '실행 타임라인 피드',
  'Document Trace Desk Snapshot': '문서 추적 데스크 스냅샷',
  'Document Trace Desk Queue': '문서 추적 데스크 대기열',
  'Document Trace Desk Feed': '문서 추적 데스크 피드',
  'Alternative Decision Desk Snapshot': '대체 의사결정 데스크 스냅샷',
  'Alternative Decision Desk Queue': '대체 의사결정 데스크 대기열',
  'Alternative Decision Desk Feed': '대체 의사결정 데스크 피드',
  'ESG-Aware Scoring Desk Snapshot': 'ESG 반영 점수 데스크 스냅샷',
  'ESG-Aware Scoring Desk Queue': 'ESG 반영 점수 데스크 대기열',
  'ESG-Aware Scoring Desk Feed': 'ESG 반영 점수 데스크 피드',
  'Decision Governance Board Snapshot': '의사결정 거버넌스 보드 스냅샷',
  'Decision Governance Board Queue': '의사결정 거버넌스 보드 대기열',
  'Decision Governance Board Feed': '의사결정 거버넌스 보드 피드',
  'Governance Ledger Snapshot': '거버넌스 원장 스냅샷',
  'Governance Ledger Queue': '거버넌스 원장 대기열',
  'Governance Ledger Feed': '거버넌스 원장 피드',
  'Ops Collaboration Room Snapshot': '운영 협업 룸 스냅샷',
  'Ops Collaboration Room Queue': '운영 협업 룸 대기열',
  'Ops Collaboration Room Feed': '운영 협업 룸 피드',
  'Alert Channel Center Snapshot': '알림 채널 센터 스냅샷',
  'Alert Channel Center Queue': '알림 채널 센터 대기열',
  'Alert Channel Center Feed': '알림 채널 센터 피드',
  'Rule & Escalation Matrix Snapshot': '규칙 및 에스컬레이션 매트릭스 스냅샷',
  'Rule & Escalation Matrix Queue': '규칙 및 에스컬레이션 매트릭스 대기열',
  'Rule & Escalation Matrix Feed': '규칙 및 에스컬레이션 매트릭스 피드',
  'Main Buyer': '메인 발주사',
  '24/7 operations': '24시간 운영',
  'delay threshold': '지연 임계치',
  'top exposure': '최상위 노출',
  'Order Desk': '발주 데스크',
  'buyer ops': '발주사 운영',
  'priority queue': '우선순위 큐',
  'mixed lanes': '혼합 레인',
  'PO Manager': '발주 관리자',
  Approvals: '승인',
  'approval lead': '승인 담당',
  'budget sync': '예산 동기화',
  Domestic: '국내',
  'warehouse linked': '창고 연계',
  'Vendor Office': '협력사 운영실',
  Partner: '파트너',
  Global: '글로벌',
  'control owner': '관리 담당',
  'tier review': '등급 검토',
  'multi-org': '다중 조직',
  'Network Ops': '네트워크 운영',
  Map: '지도',
  topology: '토폴로지',
  'tier 1-3': '1차-3차',
  'Quality Team': '품질팀',
  Expiry: '만료',
  'doc control': '문서 관리',
  'renewal queue': '갱신 대기열',
  'high volume': '고물량',
  'Response Ops': '대응 운영',
  Event: '이벤트',
  Transit: '운송',
  'event owner': '이벤트 담당',
  playbook: '플레이북',
  'cross-border': '국경 간',
  'Recovery Lead': '복구 리드',
  Timeline: '타임라인',
  Mixed: '혼합',
  'timeline owner': '일정 담당',
  'milestone flow': '마일스톤 흐름',
  'factory to port': '공장-항만',
  'Doc Control': '문서 관리',
  Trace: '추적',
  Compliance: '컴플라이언스',
  'trace owner': '추적 담당',
  'document chain': '문서 체인',
  'cross-team': '부서 간',
  'Decision Desk': '의사결정 데스크',
  Option: '대안',
  'Tier 1-2': '1차-2차',
  'recommendation owner': '권고안 담당',
  'supplier fit': '공급처 적합도',
  'coverage ready': '커버리지 준비',
  'ESG Desk': 'ESG 데스크',
  Scoring: '점수화',
  'policy owner': '정책 담당',
  'risk weighted': '리스크 가중',
  'origin mix': '원산지 혼합',
  'Gov Board': '거버넌스 위원회',
  Policy: '정책',
  Enterprise: '전사',
  'decision owner': '의사결정 담당',
  acceptance: '수용 관리',
  'all orgs': '전 조직',
  'Audit Lead': '감사 리드',
  'ledger owner': '원장 담당',
  'acceptance history': '수용 이력',
  'All pages': '전 페이지',
  'route linked': '라우트 연계',
  'Ops Channel': '운영 채널',
  Threads: '스레드',
  'Cross-org': '조직 간',
  'room owner': '채널 담당',
  'handoff ready': '인수인계 준비',
  'buyer + supplier': '발주사 + 협력사',
  'Alert Desk': '알림 데스크',
  Delivery: '전달',
  'All channels': '전체 채널',
  'channel routing': '채널 라우팅',
  'channel policy': '채널 정책',
  'email/slack/sms': '이메일/슬랙/SMS',
  'Policy Admin': '정책 관리자',
  Threshold: '임계치',
  'System-wide': '시스템 전역',
  'rule manager': '규칙 담당',
  'escalation logic': '에스컬레이션 로직',
  'auto actions': '자동 조치',
  'Primary lane': '주요 레인',
  Monitoring: '모니터링',
  'Backup source': '백업 공급처',
  Ready: '준비 완료',
  'Exception review': '예외 검토',
  Pending: '대기',
  'Impact orders refreshed from orchestration engine.': '오케스트레이션 엔진 기준으로 영향 주문을 새로 고침했습니다.',
  'Delay threshold crossed for two suppliers.': '두 협력사에서 지연 임계치를 초과했습니다.',
  'Recovery candidates prepared for operator review.': '운영자 검토용 복구 후보를 준비했습니다.',
  'Priority stack re-ranked after ETA change.': 'ETA 변경 후 우선순위를 다시 정렬했습니다.',
  'Two orders moved to supplier backup plan.': '두 건의 주문을 백업 공급처 계획으로 전환했습니다.',
  'Budget owner approval still pending on one line.': '한 라인에서 예산 담당 승인 대기가 계속되고 있습니다.',
  'Three urgent approvals moved to fast lane.': '긴급 승인 3건을 빠른 처리 레인으로 이동했습니다.',
  'Budget variance attached to impacted PO batch.': '영향 발주 묶음에 예산 편차 정보를 연결했습니다.',
  'ETA recalculation completed for delayed shipment.': '지연 선적의 ETA 재계산을 완료했습니다.',
  'One supplier moved to watchlist after KPI drop.': 'KPI 하락 이후 협력사 1곳을 감시 목록으로 이동했습니다.',
  'Onboarding packet completed for new backup vendor.': '신규 백업 벤더의 온보딩 패킷을 완료했습니다.',
  'Tier-level reassessment scheduled for next review.': '다음 검토에서 등급 재평가를 진행하도록 예약했습니다.',
  'Singapore congestion increased route stress.': '싱가포르 혼잡으로 경로 부담이 증가했습니다.',
  'Tier-2 backup path confirmed for APAC lane.': 'APAC 레인용 2차 백업 경로를 확정했습니다.',
  'Supplier health score recalculated after ESG event.': 'ESG 이벤트 이후 협력사 건전성 점수를 다시 계산했습니다.',
  'Two certificates enter 14-day renewal window.': '인증 2건이 14일 갱신 구간에 진입했습니다.',
  'Lot evidence missing on one export batch.': '수출 배치 1건에서 lot 증빙이 누락됐습니다.',
  'Quality hold released after inspection upload.': '검수 업로드 후 품질 보류를 해제했습니다.',
  'Delayed shipment rerouted through alternate lane.': '지연 선적을 대체 레인으로 우회 조치했습니다.',
  'Supplier issue converted into recovery workflow.': '협력사 이슈를 복구 워크플로로 전환했습니다.',
  'Ops team accepted recommended mitigation path.': '운영팀이 권고된 완화 경로를 수용했습니다.',
  'Recommendation accepted and queued for execution.': '권고안을 수용해 실행 대기열에 올렸습니다.',
  'Warehouse reslotting reduced backlog by 11%.': '창고 재슬로팅으로 적체를 11% 줄였습니다.',
  'Final ETA recalculated after transport change.': '운송 변경 이후 최종 ETA를 다시 계산했습니다.',
  'Document bundle linked to delayed shipment.': '문서 묶음을 지연 선적과 연결했습니다.',
  'Missing origin proof requested from supplier.': '누락된 원산지 증빙을 협력사에 요청했습니다.',
  'Compliance packet exported for governance review.': '컴플라이언스 패킷을 거버넌스 검토용으로 내보냈습니다.',
  'Backup supplier scored above target threshold.': '백업 공급처 점수가 목표 임계치 이상으로 확인됐습니다.',
  'Cost delta attached for governance review.': '거버넌스 검토용 비용 차이를 첨부했습니다.',
  'Accepted recommendation moved into execution lane.': '수용된 권고안을 실행 레인으로 이동했습니다.',
  'Origin risk increased for one supplier cluster.': '협력사 군집 1곳의 원산지 리스크가 상승했습니다.',
  'Recommendation score dropped below policy floor.': '권고안 점수가 정책 하한선 아래로 떨어졌습니다.',
  'Sustainability evidence restored ranking on backup vendor.': '지속가능성 증빙 반영으로 백업 벤더 순위가 회복됐습니다.',
  'One recommendation escalated to board review.': '권고안 1건을 위원회 검토로 에스컬레이션했습니다.',
  'Recovery score added to post-evaluation ledger.': '복구 점수를 사후평가 원장에 추가했습니다.',
  'Governance owner requested audit evidence update.': '거버넌스 담당자가 감사 증빙 업데이트를 요청했습니다.',
  'Approval reason captured for supplier switch.': '공급처 전환에 대한 승인 사유를 기록했습니다.',
  'Rejected path logged with evidence reference.': '반려 경로를 증빙 참조와 함께 기록했습니다.',
  'Audit export scheduled for compliance handoff.': '감사 내보내기를 컴플라이언스 인계 일정에 등록했습니다.',
  'Supplier response posted in escalation room.': '협력사 응답을 에스컬레이션 룸에 게시했습니다.',
  'Ops note pinned for recovery follow-up.': '복구 후속조치용 운영 메모를 고정했습니다.',
  'Unread alert converted into collaboration thread.': '읽지 않은 알림을 협업 스레드로 전환했습니다.',
  'Unread risk alert escalated to duty operator.': '미확인 리스크 알림을 당직 운영자에게 에스컬레이션했습니다.',
  'Delivery channel switched for supplier incident.': '협력사 사고 대응 전달 채널을 변경했습니다.',
  'Topic policy updated after missed acknowledgement.': '미확인 응답 이후 토픽 정책을 업데이트했습니다.',
  'Delay threshold tuned for ocean freight lane.': '해상 운송 레인용 지연 임계치를 조정했습니다.',
  'ESG alert rule linked to recommendation penalty.': 'ESG 경보 규칙을 권고안 감점 로직에 연결했습니다.',
  'Auto escalation target updated for night shift.': '야간 근무 기준 자동 에스컬레이션 대상을 업데이트했습니다.',
  'NETWORK DENSITY': '네트워크 밀도',
  'RISK INDEX (AGGREGATE)': '리스크 지수 (종합)',
  'ANOMALIES DETECTED': '탐지된 이상 징후',
  'ACTIVE SUPPLIER REGISTRY': '활성 협력사 레지스트리',
  'SEARCH NODES...': '거점 검색...',
  'CRITICAL VARIANCE DETECTED': '치명적 편차 감지',
  'GEOPOLITICAL STABILITY': '지정학 안정성',
  'LOGISTICS LATENCY': '물류 지연도',
  'SHANGHAI PORT CONGESTION [+12H]': '상하이 항만 혼잡 [+12시간]',
  'SUEZ CANAL CLEARANCE LATENCY': '수에즈 운하 통과 지연',
  Operational: '운영 중',
  'Delay Reported': '지연 보고',
  Latency: '지연',
  LOW: '낮음',
  CRITICAL: '심각',
  STABLE: '안정',
  WARNING: '경고',
  Nordics: '북유럽',
  'East Asia': '동아시아',
  DACH: '독일권',
  EMEA: 'EMEA',
  'North Star Logistics': '노스스타 물류',
  'Pacific Chip Fab': '퍼시픽 칩 팹',
  'Bavaria Motor Works': '바바리아 모터웍스',
  'Suez Marine Route': '수에즈 해상 루트',
  'TX-990218 lane delay escalation active': 'TX-990218 레인 지연 에스컬레이션 활성',
  'Warehouse overflow pressure at New Jersey': '뉴저지 창고 과적 압박',
  'Open Orchestration': '오케스트레이션 실행',
  'Export Control Tower Data': '컨트롤 타워 데이터 내보내기',
  '샘플 모달이다. 이후 실제 오케스트레이션 실행 플로우를 이 자리에 연결하면 된다.': '샘플 모달이다. 이후 실제 오케스트레이션 실행 플로우를 이 자리에 연결하면 된다.',
  '샘플 데이터 내보내기 모달이다. 실제 연결 시 파일 다운로드 API 또는 백엔드 export job을 붙이면 된다.': '샘플 데이터 내보내기 모달이다. 실제 연결 시 파일 다운로드 API 또는 백엔드 export job을 붙이면 된다.',
  '현재 영향 주문, 리스크 이벤트, 복구 ETA를 기준으로 제안 액션을 검토하는 샘플 단계다.': '현재 영향 주문, 리스크 이벤트, 복구 ETA를 기준으로 제안 액션을 검토하는 샘플 단계다.',
  '실제 연결 시에는 워크플로우 실행 API 호출 또는 상세 패널 이동을 붙이면 된다.': '실제 연결 시에는 워크플로우 실행 API 호출 또는 상세 패널 이동을 붙이면 된다.',
  실행: '실행',
  닫기: '닫기',
  '운영 테이블, KPI, 이벤트 큐를 CSV 묶음으로 저장': '운영 테이블, KPI, 이벤트 큐를 CSV 묶음으로 저장',
  '현재 화면 상태와 리스크 노드를 JSON 스냅샷으로 저장': '현재 화면 상태와 리스크 노드를 JSON 스냅샷으로 저장',
  'CSV 내보내기': 'CSV 내보내기',
  'JSON 내보내기': 'JSON 내보내기',
  Identity: '신원 정보',
  'Operator Snapshot': '운영자 스냅샷',
  'Contact & Credentials': '연락처 및 접근 정보',
  'Access Details': '접근 상세',
  'Organization Context': '조직 컨텍스트',
  'Auth Organization Entity': '인증 조직 엔티티',
  'Login History': '로그인 이력',
  'Auth Access Trace': '접근 추적',
  'User Public ID': '사용자 공개 ID',
  'User ID': '사용자 ID',
  'Login ID': '로그인 ID',
  'Full Name': '전체 이름',
  'Last Sign-In': '마지막 로그인',
  'Password Changed': '비밀번호 변경일',
  Email: '이메일',
  Phone: '전화번호',
  'Job Title': '직책',
  'Session Policy': '세션 정책',
  'JWT + role claim + organizationPublicId claim': 'JWT + 역할 클레임 + organizationPublicId 클레임',
  'Organization Public ID': '조직 공개 ID',
  'Organization Type': '조직 유형',
  'Organization Name': '조직명',
  'Business No': '사업자 번호',
  'Contact Owner': '담당자',
  '시스템 관리자 / System Administrator': '시스템 관리자',
  '시스템관리자 / System Admin': '시스템 관리자',
  'Success / 15:42 KST': '성공 / 15:42 KST',
  'Success / 09:11 KST': '성공 / 09:11 KST',
  'Failure / 08:58 KST': '실패 / 08:58 KST',
  'IP 10.10.2.44 · Mozilla/5.0 (Macintosh; Intel Mac OS X) · failureReason = null': 'IP 10.10.2.44 · Mozilla/5.0 (Macintosh; Intel Mac OS X) · 실패 사유 = 없음',
  'IP 10.10.2.21 · Chrome 135 · token issued with role + organizationPublicId': 'IP 10.10.2.21 · Chrome 135 · role + organizationPublicId 포함 토큰 발급',
  'IP 10.10.2.21 · failureReason = INVALID_PASSWORD': 'IP 10.10.2.21 · 실패 사유 = INVALID_PASSWORD',
  Success: '성공',
  Failure: '실패',
  Security: '보안',
  'Last password rotation tracked by passwordChangedAt and login history correlation': '마지막 비밀번호 변경 시점은 passwordChangedAt과 로그인 이력 상관관계로 추적됩니다.',
  'Recommendation Adoption': '권고안 수용률',
  'Recovery Success Rate': '복구 성공률',
  'Open Governance Reviews': '열린 거버넌스 검토',
  'Active Collaboration Rooms': '활성 협업 룸',
  'ETA restored in 42h avg': '평균 42시간 내 ETA 복구',
  '2 overdue escalations': '기한 초과 에스컬레이션 2건',
  '5 critical channels pinned': '중요 채널 5건 고정',
  ACTIVE: '활성',
  ADMIN: '관리자',
  ORG_ADMIN: '조직 관리자',
  LOGIN_HISTORY: '로그인 이력',
}

export function resolveDefaultCopy(text: string, language: AppLanguage) {
  if (language === 'en') return text
  return KO_DEFAULT_COPY[text] ?? text
}
