import type { NavEntry, NavSection, OrganizationType, PageKey } from '../types'

export const PAGE_PATHS: Record<PageKey, string> = {
  controlTower: '/control-tower',
  impactOrders: '/impact-orders',
  supplierNetwork: '/supplier-network',
  ordersDesk: '/orders-desk',
  supplierControl: '/supplier-control',
  certificateWatch: '/certificate-watch',
  shipmentOps: '/risk-events',
  recoveryTracking: '/recovery-tracking',
  documents: '/documents',
  recommendations: '/recommendations',
  esgSignals: '/esg-signals',
  governance: '/governance',
  auditTrail: '/audit-trail',
  collaboration: '/collaboration',
  notificationsCenter: '/notifications-center',
  riskRules: '/risk-rules',
  profile: '/profile',
  systemSpec: '/system-spec',
}

export function isPageKey(value: string | undefined): value is PageKey {
  return value !== undefined && value in PAGE_PATHS
}

export const ORGANIZATION_LABELS: Record<OrganizationType, string> = {
  mainBuyer: 'Main Buyer Ops',
  supplier: 'Tier-1 Supplier',
  admin: 'Platform Admin',
}

export const NAV_ITEMS: NavEntry[] = [
  {
    key: 'controlTower',
    label: 'Control Tower',
    icon: 'dashboard',
    description: '실시간 리스크 오케스트레이션',
    pageSubtitle: '영향 주문, 납기 리스크, 실시간 이슈 모니터링',
    section: 'monitoring',
    organizations: ['mainBuyer', 'admin'],
    badge: 'LIVE',
    badgeTone: 'ok',
  },
  {
    key: 'impactOrders',
    label: 'Impact Orders',
    icon: 'receipt_long',
    description: '영향 PO와 납기 복구 우선순위',
    pageSubtitle: '영향 발주, 회복 ETA, 우선순위 기준 실행 큐',
    section: 'monitoring',
    organizations: ['mainBuyer'],
    badge: '12',
    badgeTone: 'crit',
  },
  {
    key: 'supplierNetwork',
    label: 'Supplier Network',
    icon: 'hub',
    description: '1차-3차 공급망 가시화',
    pageSubtitle: '공급망 tier 연결, 병목 위치, 대체 경로 가시화',
    section: 'monitoring',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    badge: '248',
    badgeTone: 'info',
  },
  {
    key: 'ordersDesk',
    label: 'Order Control',
    icon: 'shopping_cart',
    description: '발주 승인, ETA, 우선순위 운영',
    pageSubtitle: '발주 승인 상태, ETA 변동, 공급처별 우선순위 제어',
    section: 'operations',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    badge: '12',
    badgeTone: 'warn',
  },
  {
    key: 'supplierControl',
    label: 'Supplier Control',
    icon: 'domain',
    description: '협력사 상태, 등급, 온보딩 관리',
    pageSubtitle: '협력사 등급, 인증, 온보딩 및 성과 상태 관리',
    section: 'operations',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    badge: '6',
    badgeTone: 'info',
  },
  {
    key: 'certificateWatch',
    label: 'Certificate Watch',
    icon: 'workspace_premium',
    description: '인증 만료와 품질 리스크 사전 감시',
    pageSubtitle: '인증 만료, lot 이슈, 품질 문서 상태 사전 감시',
    section: 'monitoring',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    badge: '4',
    badgeTone: 'warn',
  },
  {
    key: 'shipmentOps',
    label: 'Risk Events',
    icon: 'warning',
    description: 'supplier_issue / shipment_delayed',
    pageSubtitle: '이벤트 기반 물류 지연 대응과 오케스트레이션',
    section: 'response',
    organizations: ['mainBuyer', 'supplier'],
    badge: '5',
    badgeTone: 'crit',
  },
  {
    key: 'recoveryTracking',
    label: 'Recovery Tracking',
    icon: 'timeline',
    description: '복구 ETA, 실행 상태, 병목 해소 추적',
    pageSubtitle: '복구 ETA, 조치 이행, 병목 해소 상태 추적',
    section: 'response',
    organizations: ['mainBuyer', 'supplier'],
    badge: '31',
    badgeTone: 'warn',
  },
  {
    key: 'documents',
    label: 'Docs & Certs',
    icon: 'description',
    description: '품질 이슈, lot, 인증 추적',
    pageSubtitle: '품질, lot, 인증, 문서 상태 추적',
    section: 'response',
    organizations: ['mainBuyer', 'supplier', 'admin'],
  },
  {
    key: 'recommendations',
    label: 'Recommendations',
    icon: 'insights',
    description: '대체 1차 / 2차 권고안',
    pageSubtitle: '추천 엔진 기반 대체 공급처 의사결정',
    section: 'response',
    organizations: ['mainBuyer', 'supplier'],
    badge: '8',
    badgeTone: 'warn',
  },
  {
    key: 'esgSignals',
    label: 'ESG Signals',
    icon: 'eco',
    description: 'ESG 경보와 권고안 점수 반영',
    pageSubtitle: 'ESG 경보, 원산지, 지속가능성 점수 반영',
    section: 'response',
    organizations: ['mainBuyer', 'admin'],
    badge: '3',
    badgeTone: 'info',
  },
  {
    key: 'governance',
    label: 'Governance',
    icon: 'gavel',
    description: '수용 여부와 사후평가 관리',
    pageSubtitle: '권고안 수용, 실행, 회복 성과, 사후평가',
    section: 'governance',
    organizations: ['mainBuyer', 'supplier', 'admin'],
  },
  {
    key: 'auditTrail',
    label: 'Audit Trail',
    icon: 'fact_check',
    description: '권고안 이력, 수용 사유, 감사 로그',
    pageSubtitle: '권고안 이력, 승인 기록, 감사 로그 추적',
    section: 'governance',
    organizations: ['mainBuyer', 'admin'],
  },
  {
    key: 'collaboration',
    label: 'Collaboration',
    icon: 'forum',
    description: '실시간 대응 협업과 알림',
    pageSubtitle: '운영자, 협력사, 알림 흐름의 실시간 협업',
    section: 'governance',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    badge: '13',
    badgeTone: 'info',
  },
  {
    key: 'notificationsCenter',
    label: 'Notifications',
    icon: 'notifications',
    description: '채널 정책과 읽지 않은 경보 관리',
    pageSubtitle: '알림 채널, 미확인 경보, topic 상태 관리',
    section: 'system',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    badge: '9',
    badgeTone: 'crit',
  },
  {
    key: 'riskRules',
    label: 'Risk Rules',
    icon: 'tune',
    description: '이벤트 규칙과 임계치 정책 관리',
    pageSubtitle: '리스크 룰, 임계치, 자동 에스컬레이션 정책 관리',
    section: 'system',
    organizations: ['mainBuyer', 'admin'],
  },
  {
    key: 'profile',
    label: 'Profile',
    icon: 'account_circle',
    description: '운영자 계정, 권한, 알림 정책',
    pageSubtitle: '운영자 권한, 알림 정책, KPI와 감사 이력',
    section: 'governance',
    organizations: ['mainBuyer', 'supplier', 'admin'],
  },
]

export const NAV_SECTION_LABELS: Record<NavSection, string> = {
  monitoring: 'Monitoring',
  operations: 'Operations',
  response: 'Response',
  governance: 'Governance',
  system: 'System',
}
