import type { NavEntry, NavSection, OrganizationType, PageKey } from '../types'

export const PAGE_PATHS: Record<PageKey, string> = {
  controlTower: '/dashboard',
  impactOrders: '/impact',
  supplierNetwork: '/network',
  ordersDesk: '/orders',
  supplierControl: '/suppliers',
  items: '/items',
  inventory: '/inventory',
  shipments: '/shipments',
  settlements: '/settlements',
  logisticsNodes: '/logistics-nodes',
  returns: '/returns',
  certificateWatch: '/certificates',
  certificateReview: '/certificate-review',
  shipmentOps: '/risks',
  recoveryTracking: '/recovery-tracking',
  documents: '/documents',
  recommendations: '/recommendations',
  esgSignals: '/esg-signals',
  governance: '/governance',
  evaluation: '/evaluation',
  vendorKpi: '/vendor-kpi',
  acceptance: '/acceptance',
  auditTrail: '/audit',
  collaboration: '/collaboration',
  notificationsCenter: '/notifications',
  riskRules: '/risk-rules',
  settings: '/settings',
  profile: '/profile',
  systemSpec: '/system-spec',
  organizationManagement: '/organization-management',
  organizationProfile: '/organizations',
}

export function isPageKey(value: string | undefined): value is PageKey {
  return value !== undefined && value in PAGE_PATHS
}

export const ORGANIZATION_LABELS: Record<OrganizationType, string> = {
  mainBuyer: '메인 발주 운영',
  supplier: '1차 협력사',
  admin: '플랫폼 관리자',
}

export const NAV_ITEMS: NavEntry[] = [
  {
    key: 'organizationProfile',
    label: '조직 프로필',
    icon: 'business',
    description: '검색 결과에서 진입하는 읽기 전용 조직 정보입니다.',
    pageSubtitle: '조직 기본정보와 등록 물품을 확인합니다.',
    section: 'system',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    hidden: true,
  },

  {
    key: 'controlTower',
    label: '대시보드',
    icon: 'dashboard',
    description: '운영 대시보드와 핵심 위험 지표',
    pageSubtitle: '전체 공급망 운영 현황과 핵심 경보 모니터링',
    section: 'monitoring',
    organizations: ['mainBuyer', 'admin'],
    // 컨트롤 타워 메뉴 임시 숨김: 삭제 금지, 필요 시 hidden 해제
    hidden: true,
    badge: '실시간',
    badgeTone: 'ok',
  },
  {
    key: 'supplierNetwork',
    label: '공급망 네트워크',
    icon: 'hub',
    description: '공급망 네트워크 시각화',
    pageSubtitle: 'Tier 연결, 병목 지점, 대체 경로 가시화',
    section: 'monitoring',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    // 컨트롤 타워 메뉴 임시 숨김: 삭제 금지, 필요 시 hidden 해제
    hidden: true,
    badge: '248',
    badgeTone: 'info',
  },
  {
    key: 'shipmentOps',
    label: '리스크 이벤트',
    icon: 'warning',
    description: 'supplier_issue / shipment_delayed',
    pageSubtitle: '이벤트 기반 지연 대응과 리스크 오케스트레이션',
    section: 'monitoring',
    organizations: ['mainBuyer', 'supplier'],
    // 컨트롤 타워 메뉴 임시 숨김: 삭제 금지, 필요 시 hidden 해제
    hidden: true,
    badge: '5',
    badgeTone: 'crit',
  },
  {
    key: 'impactOrders',
    label: '영향 분석',
    icon: 'receipt_long',
    description: '영향 분석과 우선순위 주문',
    pageSubtitle: '영향 주문, ETA 편차, 우선순위 실행 큐',
    section: 'monitoring',
    organizations: ['mainBuyer'],
    // 컨트롤 타워 메뉴 임시 숨김: 삭제 금지, 필요 시 hidden 해제
    hidden: true,
    badge: '12',
    badgeTone: 'crit',
  },
  {
    key: 'logisticsNodes',
    label: '창고 관리',
    icon: 'warehouse',
    description: '창고 등록, 조회, 상태 관리',
    pageSubtitle: '창고 정보와 활성 상태를 운영 화면에서 관리',
    section: 'operations',
    organizations: ['mainBuyer', 'supplier'],
  },
  {
    key: 'items',
    label: '품목 관리',
    icon: 'inventory_2',
    description: '품목 관리 및 공급역량',
    pageSubtitle: 'SKU, 재고, 재발주점, 공급사 기준 운영',
    section: 'operations',
    organizations: ['supplier'],
  },
  {
    key: 'inventory',
    label: '재고 관리',
    icon: 'inventory',
    description: '품목별 유통기한 재고 관리',
    pageSubtitle: '제조일, 유통기한, 예약 수량 기준 재고를 관리합니다.',
    section: 'operations',
    organizations: ['supplier'],
  },
  {
    key: 'ordersDesk',
    label: '주문 관리',
    icon: 'shopping_cart',
    description: '발주 승인, ETA, 우선순위 운영',
    pageSubtitle: '발주 승인 상태, ETA 변동, 공급처별 우선순위 제어',
    section: 'operations',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    badge: '12',
    badgeTone: 'warn',
  },
  {
    key: 'supplierControl',
    label: '협력사 관리',
    icon: 'domain',
    description: '협력사 상태, 등급, 온보딩 관리',
    pageSubtitle: '협력사 등급, 인증, 온보딩 및 성과 상태 관리',
    section: 'operations',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    badge: '6',
    badgeTone: 'info',
  },
  {
    key: 'shipments',
    label: '출하',
    icon: 'local_shipping',
    description: '출하 목록, 추적, ETA, 예외 관리',
    pageSubtitle: '출하 흐름과 추적 상태를 관리합니다',
    section: 'operations',
    organizations: ['mainBuyer', 'supplier'],
  },
  {
    key: 'returns',
    label: '반품',
    icon: 'assignment_return',
    description: '반품 요청 및 처리 관리',
    pageSubtitle: '요청, 승인, 회수, 입고 상태와 이력 추적',
    section: 'operations',
    organizations: ['mainBuyer', 'supplier'],
    badge: '1',
    badgeTone: 'warn',
  },
  {
    key: 'settlements',
    label: '정산',
    icon: 'request_quote',
    description: '정산 목록, 상세, 승인, 취소 관리',
    pageSubtitle: '정산 처리 상태와 승인 흐름을 관리합니다',
    section: 'operations',
    organizations: ['mainBuyer', 'supplier'],
  },
  {
    key: 'certificateWatch',
    label: '인증서',
    icon: 'workspace_premium',
    description: '인증서 유효성 및 갱신 관리',
    pageSubtitle: '인증 유형, 만료일, 협력사 상태 추적',
    section: 'response',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    badge: '4',
    badgeTone: 'warn',
  },
  {
    key: 'recoveryTracking',
    label: '복구 추적',
    icon: 'timeline',
    description: '복구 ETA, 실행 상태, 병목 해소 추적',
    pageSubtitle: '복구 ETA, 조치 이행, 병목 해소 상태 추적',
    section: 'response',
    organizations: ['mainBuyer', 'supplier'],
    badge: '31',
    badgeTone: 'warn',
    hidden: true,
  },
  {
    key: 'documents',
    label: '문서 관리',
    icon: 'description',
    description: '문서 보관과 OCR 검증 관리',
    pageSubtitle: '송장, BOL, OCR 검증과 문서 상태 추적',
    section: 'response',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    hidden: true,
  },
  {
    key: 'recommendations',
    label: '권고안',
    icon: 'insights',
    description: '대체 1차 / 2차 권고안',
    pageSubtitle: '추천 엔진 기반 대체 공급처 의사결정',
    section: 'monitoring',
    organizations: ['mainBuyer', 'supplier'],
    // 컨트롤 타워 메뉴 임시 숨김: 삭제 금지, 필요 시 hidden 해제
    hidden: true,
    badge: '8',
    badgeTone: 'warn',
  },
  {
    key: 'esgSignals',
    label: 'ESG 시그널',
    icon: 'eco',
    description: 'ESG 경보와 권고안 점수 반영',
    pageSubtitle: 'ESG 경보, 원산지, 지속가능성 점수 반영',
    section: 'response',
    organizations: ['mainBuyer', 'admin'],
    badge: '3',
    badgeTone: 'info',
    hidden: true,
  },
  {
    key: 'governance',
    label: '거버넌스',
    icon: 'gavel',
    description: '수용 여부와 사후평가 관리',
    pageSubtitle: '권고안 수용, 실행, 회복 성과, 사후평가',
    section: 'governance',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    hidden: true,
  },
  {
    key: 'evaluation',
    label: '평가',
    icon: 'analytics',
    description: '수용 결과와 성과 평가 현황',
    pageSubtitle: '권고안 반영 결과, 평가 점수, 월별 추이 관리',
    section: 'governance',
    organizations: ['mainBuyer', 'admin'],
    hidden: true,
  },
  {
    key: 'vendorKpi',
    label: '벤더 KPI',
    icon: 'monitoring',
    description: '협력사 KPI 대시보드',
    pageSubtitle: '납기, 품질, ESG, 대응속도 기준 KPI 비교',
    section: 'governance',
    organizations: ['mainBuyer', 'admin'],
    hidden: true,
  },
  {
    key: 'acceptance',
    label: '수용률',
    icon: 'rule',
    description: '권고안 수용률 현황',
    pageSubtitle: '수용률, 거절 사유, 긴급도별 반영 상태 추적',
    section: 'governance',
    organizations: ['mainBuyer', 'admin'],
    hidden: true,
  },
  {
    key: 'auditTrail',
    label: '이벤트 발행 로그',
    icon: 'manage_search',
    description: 'Kafka 이벤트 발행 로그',
    pageSubtitle: 'Kafka 이벤트 발행 이력 추적',
    section: 'system',
    organizations: ['admin'],
  },
  {
    key: 'collaboration',
    label: '협업',
    icon: 'forum',
    description: '실시간 대응 협업과 알림',
    pageSubtitle: '운영자, 협력사, 알림 흐름의 실시간 협업',
    section: 'governance',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    badge: '13',
    badgeTone: 'info',
    hidden: true,
  },
  {
    key: 'certificateReview',
    label: '인증서 심사',
    icon: 'fact_check',
    description: '인증서 신청 승인과 반려 처리',
    pageSubtitle: '심사 요청 인증서를 검토하고 승인 또는 반려합니다.',
    section: 'system',
    organizations: ['admin'],
  },
  {
    key: 'notificationsCenter',
    label: '알림',
    icon: 'notifications',
    description: '채널 정책과 읽지 않은 경보 관리',
    pageSubtitle: '알림 채널, 미확인 경보, topic 상태 관리',
    section: 'system',
    organizations: ['mainBuyer', 'supplier', 'admin'],
  },
  {
    key: 'riskRules',
    label: '리스크 규칙',
    icon: 'tune',
    description: '이벤트 규칙과 임계치 정책 관리',
    pageSubtitle: '리스크 룰, 임계치, 자동 에스컬레이션 정책 관리',
    section: 'system',
    organizations: ['mainBuyer', 'admin'],
  },
  {
    key: 'settings',
    label: '설정',
    icon: 'settings',
    description: '조직, 사용자, 알림, API 키 정책',
    pageSubtitle: '시스템 전역 설정, 사용자, 보안 정책 관리',
    section: 'system',
    organizations: ['admin'],
  },
    {
    key: 'organizationManagement',
    label: '조직관리',
    icon: 'apartment',
    description: '조직 목록 조회와 조직 정보 수정',
    pageSubtitle: '플랫폼 관리자와 조직 대표자가 조직 정보를 관리하는 화면',
    section: 'system',
    organizations: ['mainBuyer', 'supplier', 'admin'],
  },

  {
    key: 'systemSpec',
    label: '시스템 스펙',
    icon: 'schema',
    description: '디자인 스펙과 화면 규격 문서',
    pageSubtitle: 'Kinetic Blueprint 시스템 스펙 문서',
    section: 'system',
    organizations: ['admin'],
    hidden: true,
  },
  {
    key: 'profile',
    label: '프로필',
    icon: 'account_circle',
    description: '운영자 계정, 권한, 알림 정책',
    pageSubtitle: '운영자 권한, 알림 정책, KPI와 감사 이력',
    section: 'governance',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    hidden: true,
  },
]

export const NAV_SECTION_LABELS: Record<NavSection, string> = {
  monitoring: '컨트롤 타워',
  operations: '공급망 운영',
  response: '문서 / 인증',
  governance: '거버넌스',
  system: '시스템',
}
