import type { NavEntry, NavSection, OrganizationType, PageKey } from '../types'

export const PAGE_PATHS: Record<PageKey, string> = {
  designSystem: '/design-system',
  controlTower: '/dashboard',
  impactOrders: '/impact',
  supplierNetwork: '/network',
  ordersDesk: '/orders',
  supplierControl: '/suppliers',
  items: '/items',
  lots: '/lots',
  shipments: '/shipments',
  settlements: '/settlements',
  logisticsNodes: '/logistics-nodes',
  returns: '/returns',
  certificateWatch: '/certificates',
  shipmentOps: '/risks',
  recoveryTracking: '/recovery-tracking',
  documents: '/documents',
  recommendations: '/recommendations',
  esgSignals: '/esg-signals',
  governance: '/governance',
  evaluation: '/evaluation',
  vendorKpi: '/vendor-kpi',
  acceptance: '/acceptance',
  auditTrail: '/audit',
  collaboration: '/collaboration',
  notificationsCenter: '/notifications',
  riskRules: '/risk-rules',
  settings: '/settings',
  profile: '/profile',
  systemSpec: '/system-spec',
}

export function isPageKey(value: string | undefined): value is PageKey {
  return value !== undefined && value in PAGE_PATHS
}

export const ORGANIZATION_LABELS: Record<OrganizationType, string> = {
  mainBuyer: 'Main Buyer Ops',
  supplier: 'Tier-1 Supplier',
  admin: 'Platform Admin',
}

export const NAV_ITEMS: NavEntry[] = [
  {
    key: 'designSystem',
    label: 'Design System',
    icon: 'palette',
    description: '토큰, 타이포, 인터랙션 기준',
    pageSubtitle: 'Kinetic Blueprint 토큰, 계층, 컴포넌트 기준',
    section: 'system',
    organizations: ['admin'],
    hidden: true,
  },
  {
    key: 'controlTower',
    label: 'Dashboard',
    icon: 'dashboard',
    description: '운영 대시보드와 핵심 위험 지표',
    pageSubtitle: '전체 공급망 운영 현황과 핵심 경보 모니터링',
    section: 'monitoring',
    organizations: ['mainBuyer', 'admin'],
    badge: 'LIVE',
    badgeTone: 'ok',
  },
  {
    key: 'supplierNetwork',
    label: 'Network',
    icon: 'hub',
    description: '공급망 네트워크 시각화',
    pageSubtitle: 'Tier 연결, 병목 지점, 대체 경로 가시화',
    section: 'monitoring',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    badge: '248',
    badgeTone: 'info',
  },
  {
    key: 'shipmentOps',
    label: 'Risk Events',
    icon: 'warning',
    description: 'supplier_issue / shipment_delayed',
    pageSubtitle: '이벤트 기반 지연 대응과 리스크 오케스트레이션',
    section: 'monitoring',
    organizations: ['mainBuyer', 'supplier'],
    badge: '5',
    badgeTone: 'crit',
  },
  {
    key: 'impactOrders',
    label: 'Impact',
    icon: 'receipt_long',
    description: '영향 분석과 우선순위 주문',
    pageSubtitle: '영향 주문, ETA 편차, 우선순위 실행 큐',
    section: 'monitoring',
    organizations: ['mainBuyer'],
    badge: '12',
    badgeTone: 'crit',
  },
  {
    key: 'ordersDesk',
    label: 'Orders',
    icon: 'shopping_cart',
    description: '발주 승인, ETA, 우선순위 운영',
    pageSubtitle: '발주 승인 상태, ETA 변동, 공급처별 우선순위 제어',
    section: 'operations',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    badge: '12',
    badgeTone: 'warn',
  },
  {
    key: 'supplierControl',
    label: 'Suppliers',
    icon: 'domain',
    description: '협력사 상태, 등급, 온보딩 관리',
    pageSubtitle: '협력사 등급, 인증, 온보딩 및 성과 상태 관리',
    section: 'operations',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    badge: '6',
    badgeTone: 'info',
  },
  {
    key: 'items',
    label: 'Items',
    icon: 'inventory_2',
    description: '품목 관리와 재고 임계치',
    pageSubtitle: 'SKU, 재고, 재발주점, 공급처 기준 운영',
    section: 'operations',
    organizations: ['mainBuyer', 'supplier', 'admin'],
  },
  {
    key: 'lots',
    label: 'LOT',
    icon: 'local_shipping',
    description: 'Lot tracking and quality control',
    pageSubtitle: 'Manage lot history, inspection, and status',
    section: 'operations',
    organizations: ['mainBuyer', 'admin'],
  },
  {
    key: 'shipments',
    label: 'Shipments',
    icon: 'local_shipping',
    description: 'Shipment list, tracking, ETA, and exceptions',
    pageSubtitle: 'Manage outbound shipment flow and tracking status',
    section: 'operations',
    organizations: ['mainBuyer', 'admin'],
  },
    {
    key: 'settlements',
    label: 'Settlements',
    icon: 'request_quote',
    description: 'Settlement list, detail, approval, and cancellation',
    pageSubtitle: 'Manage settlement processing status and approval flow',
    section: 'operations',
    organizations: ['mainBuyer', 'admin'],
  },
  {
    key: 'logisticsNodes',
    label: 'Logistics',
    icon: 'warehouse',
    description: '물류거점 등록, 조회, 상태 관리',
    pageSubtitle: '물류거점 정보와 활성 상태를 운영 화면에서 관리',
    section: 'operations',
    organizations: ['mainBuyer', 'admin'],
  },
  {
    key: 'returns',
    label: 'Returns',
    icon: 'assignment_return',
    description: '반품 요청 및 처리 관리',
    pageSubtitle: '요청, 승인, 회수, 입고 상태와 이력 추적',
    section: 'operations',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    badge: '1',
    badgeTone: 'warn',
  },
  {
    key: 'certificateWatch',
    label: 'Certificates',
    icon: 'workspace_premium',
    description: '인증서 유효성 및 갱신 관리',
    pageSubtitle: '인증 유형, 만료일, 협력사 상태 추적',
    section: 'response',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    badge: '4',
    badgeTone: 'warn',
  },
  {
    key: 'recoveryTracking',
    label: 'Recovery Tracking',
    icon: 'timeline',
    description: '복구 ETA, 실행 상태, 병목 해소 추적',
    pageSubtitle: '복구 ETA, 조치 이행, 병목 해소 상태 추적',
    section: 'response',
    organizations: ['mainBuyer', 'supplier'],
    badge: '31',
    badgeTone: 'warn',
    hidden: true,
  },
  {
    key: 'documents',
    label: 'Documents',
    icon: 'description',
    description: '문서 보관과 OCR 검증 관리',
    pageSubtitle: '송장, BOL, OCR 검증과 문서 상태 추적',
    section: 'response',
    organizations: ['mainBuyer', 'supplier', 'admin'],
  },
  {
    key: 'recommendations',
    label: 'Recommendations',
    icon: 'insights',
    description: '대체 1차 / 2차 권고안',
    pageSubtitle: '추천 엔진 기반 대체 공급처 의사결정',
    section: 'monitoring',
    organizations: ['mainBuyer', 'supplier'],
    badge: '8',
    badgeTone: 'warn',
  },
  {
    key: 'esgSignals',
    label: 'ESG Signals',
    icon: 'eco',
    description: 'ESG 경보와 권고안 점수 반영',
    pageSubtitle: 'ESG 경보, 원산지, 지속가능성 점수 반영',
    section: 'response',
    organizations: ['mainBuyer', 'admin'],
    badge: '3',
    badgeTone: 'info',
    hidden: true,
  },
  {
    key: 'governance',
    label: 'Governance',
    icon: 'gavel',
    description: '수용 여부와 사후평가 관리',
    pageSubtitle: '권고안 수용, 실행, 회복 성과, 사후평가',
    section: 'governance',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    hidden: true,
  },
  {
    key: 'evaluation',
    label: 'Evaluation',
    icon: 'analytics',
    description: '수용 결과와 성과 평가 현황',
    pageSubtitle: '권고안 반영 결과, 평가 점수, 월별 추이 관리',
    section: 'governance',
    organizations: ['mainBuyer', 'admin'],
  },
  {
    key: 'vendorKpi',
    label: 'Vendor KPI',
    icon: 'monitoring',
    description: '협력사 KPI 대시보드',
    pageSubtitle: '납기, 품질, ESG, 대응속도 기준 KPI 비교',
    section: 'governance',
    organizations: ['mainBuyer', 'admin'],
  },
  {
    key: 'acceptance',
    label: 'Acceptance',
    icon: 'rule',
    description: '권고안 수용률 현황',
    pageSubtitle: '수용률, 거절 사유, 긴급도별 반영 상태 추적',
    section: 'governance',
    organizations: ['mainBuyer', 'admin'],
  },
  {
    key: 'auditTrail',
    label: 'Audit',
    icon: 'fact_check',
    description: '시스템 감사 로그',
    pageSubtitle: '사용자, 시스템, 보안 이벤트 감사 로그',
    section: 'system',
    organizations: ['mainBuyer', 'admin', 'supplier'],
  },
  {
    key: 'collaboration',
    label: 'Collaboration',
    icon: 'forum',
    description: '실시간 대응 협업과 알림',
    pageSubtitle: '운영자, 협력사, 알림 흐름의 실시간 협업',
    section: 'governance',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    badge: '13',
    badgeTone: 'info',
    hidden: true,
  },
  {
    key: 'notificationsCenter',
    label: 'Notifications',
    icon: 'notifications',
    description: '채널 정책과 읽지 않은 경보 관리',
    pageSubtitle: '알림 채널, 미확인 경보, topic 상태 관리',
    section: 'system',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    badge: '9',
    badgeTone: 'crit',
  },
  {
    key: 'riskRules',
    label: 'Risk Rules',
    icon: 'tune',
    description: '이벤트 규칙과 임계치 정책 관리',
    pageSubtitle: '리스크 룰, 임계치, 자동 에스컬레이션 정책 관리',
    section: 'system',
    organizations: ['mainBuyer', 'admin'],
  },
  {
    key: 'settings',
    label: 'Settings',
    icon: 'settings',
    description: '조직, 사용자, 알림, API 키 정책',
    pageSubtitle: '시스템 전역 설정, 사용자, 보안 정책 관리',
    section: 'system',
    organizations: ['admin'],
  },
  {
    key: 'systemSpec',
    label: 'System Spec',
    icon: 'schema',
    description: '디자인 스펙과 화면 규격 문서',
    pageSubtitle: 'Kinetic Blueprint 시스템 스펙 문서',
    section: 'system',
    organizations: ['admin'],
    hidden: true,
  },
  {
    key: 'profile',
    label: 'Profile',
    icon: 'account_circle',
    description: '운영자 계정, 권한, 알림 정책',
    pageSubtitle: '운영자 권한, 알림 정책, KPI와 감사 이력',
    section: 'governance',
    organizations: ['mainBuyer', 'supplier', 'admin'],
    hidden: true,
  },
]

export const NAV_SECTION_LABELS: Record<NavSection, string> = {
  monitoring: 'Control Tower',
  operations: 'Supply Chain Ops',
  response: 'Documents & Certificates',
  governance: 'Governance',
  system: 'System',
}
